"""
Sigma-C WebAssembly Interface
===============================
Copyright (c) 2025 ForgottenForge.xyz

WebAssembly build system and browser interface for Sigma-C.
Provides:
1. WASMBuilder: Generates self-contained JS/HTML for browser-native analysis
2. PyodideBridge: Interface for running Sigma-C in Pyodide (Python-in-browser)
3. Build helpers for Emscripten compilation of the C++ core

SPDX-License-Identifier: AGPL-3.0-or-later OR Commercial
"""

import json
import os
import subprocess
from typing import Dict, Any, Optional
import numpy as np

from ..core.engine import Engine


class WASMBuilder:
    """
    Generate self-contained browser artifacts for Sigma-C.

    Creates JavaScript modules and HTML demos that perform criticality
    analysis entirely in the browser. Two modes:

    1. Pyodide mode (default): Uses Python-in-browser via Pyodide.
       No build step needed -- generates HTML that loads sigma-c-framework
       from PyPI directly in the browser.

    2. Emscripten mode: Compiles the C++ core to WASM.
       Requires Emscripten SDK installed.

    Usage:
        from sigma_c.api.wasm import WASMBuilder

        builder = WASMBuilder()

        # Generate a browser demo
        html = builder.generate_html_demo()
        with open('sigma_c_demo.html', 'w') as f:
            f.write(html)

        # Generate standalone JS module
        js = builder.generate_js_module()
    """

    def __init__(self, output_dir: str = '.'):
        self.output_dir = output_dir

    def generate_js_module(self) -> str:
        """
        Generate a standalone JavaScript ES module implementing
        the core Sigma-C algorithm (no dependencies).

        Returns:
            JavaScript source code string.
        """
        return """// sigma_c.js -- Browser-native criticality analysis
// Generated by sigma_c.api.wasm.WASMBuilder
// No dependencies required.

export function computeSigmaC(epsilon, observable) {
    if (epsilon.length !== observable.length || epsilon.length < 3) {
        throw new Error("epsilon and observable must have equal length >= 3");
    }

    // Compute susceptibility (numerical derivative)
    const n = epsilon.length;
    const chi = new Float64Array(n - 1);
    for (let i = 0; i < n - 1; i++) {
        const dEps = epsilon[i + 1] - epsilon[i];
        const dObs = observable[i + 1] - observable[i];
        chi[i] = Math.abs(dEps > 1e-15 ? dObs / dEps : 0.0);
    }

    // Find peak
    let peakIdx = 0;
    let chiMax = chi[0];
    let chiSum = chi[0];
    for (let i = 1; i < chi.length; i++) {
        chiSum += chi[i];
        if (chi[i] > chiMax) {
            chiMax = chi[i];
            peakIdx = i;
        }
    }

    const chiMean = chiSum / chi.length;
    const kappa = chiMean > 1e-15 ? chiMax / chiMean : 0.0;
    const sigmaC = epsilon[peakIdx];

    return {
        sigma_c: sigmaC,
        kappa: kappa,
        chi_max: chiMax,
        chi: Array.from(chi),
        peak_index: peakIdx
    };
}

export class StreamingSigmaC {
    constructor(windowSize = 100) {
        this.windowSize = windowSize;
        this.epsilonBuffer = [];
        this.observableBuffer = [];
        this.currentSigmaC = 0.0;
    }

    update(epsilon, observable) {
        this.epsilonBuffer.push(epsilon);
        this.observableBuffer.push(observable);

        if (this.epsilonBuffer.length > this.windowSize) {
            this.epsilonBuffer.shift();
            this.observableBuffer.shift();
        }

        if (this.epsilonBuffer.length >= 10) {
            const result = computeSigmaC(this.epsilonBuffer, this.observableBuffer);
            this.currentSigmaC = result.sigma_c;
        }

        return this.currentSigmaC;
    }
}
"""

    def generate_html_demo(self, title: str = "Sigma-C Browser Demo") -> str:
        """
        Generate a self-contained HTML page with interactive analysis.

        Uses the pure-JS implementation (no WASM build needed).

        Args:
            title: Page title.

        Returns:
            Complete HTML string.
        """
        js_module = self.generate_js_module()

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{ font-family: monospace; max-width: 700px; margin: 40px auto; padding: 0 20px; }}
        h1 {{ font-size: 1.4em; }}
        label {{ display: block; margin-top: 12px; font-weight: bold; }}
        input {{ width: 100%; padding: 6px; font-family: monospace; box-sizing: border-box; }}
        button {{ margin-top: 12px; padding: 8px 20px; cursor: pointer; }}
        #results {{ margin-top: 20px; background: #f4f4f4; padding: 16px; border-radius: 4px; }}
        .bar {{ background: #2563eb; height: 16px; margin: 2px 0; border-radius: 2px; }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <p>Criticality analysis running entirely in your browser.</p>

    <label>Epsilon (comma-separated):</label>
    <input type="text" id="epsilon"
           value="0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5">

    <label>Observable (comma-separated):</label>
    <input type="text" id="observable"
           value="1.0, 0.97, 0.90, 0.78, 0.55, 0.30, 0.15, 0.08, 0.04, 0.02, 0.01">

    <button onclick="analyze()">Analyze</button>

    <div id="results"></div>

    <script type="module">
{js_module}

    window.analyze = function() {{
        const epsStr = document.getElementById('epsilon').value;
        const obsStr = document.getElementById('observable').value;

        const epsilon = epsStr.split(',').map(x => parseFloat(x.trim()));
        const observable = obsStr.split(',').map(x => parseFloat(x.trim()));

        try {{
            const result = computeSigmaC(epsilon, observable);
            const maxChi = Math.max(...result.chi);

            let html = '<h2>Results</h2>';
            html += '<p><b>sigma_c:</b> ' + result.sigma_c.toFixed(4) + '</p>';
            html += '<p><b>kappa:</b> ' + result.kappa.toFixed(2) + '</p>';
            html += '<p><b>chi_max:</b> ' + result.chi_max.toFixed(4) + '</p>';
            html += '<h3>Susceptibility</h3>';

            for (let i = 0; i < result.chi.length; i++) {{
                const pct = (result.chi[i] / maxChi * 100).toFixed(0);
                const isCritical = i === result.peak_index ? ' (peak)' : '';
                html += '<div style="display:flex;align-items:center;gap:8px">';
                html += '<span style="width:50px">' + epsilon[i].toFixed(2) + '</span>';
                html += '<div class="bar" style="width:' + pct + '%"></div>';
                html += '<span>' + result.chi[i].toFixed(3) + isCritical + '</span>';
                html += '</div>';
            }}

            document.getElementById('results').innerHTML = html;
        }} catch (e) {{
            document.getElementById('results').innerHTML = '<p style="color:red">' + e.message + '</p>';
        }}
    }};
    </script>
</body>
</html>
"""

    def generate_pyodide_demo(self) -> str:
        """
        Generate an HTML demo that runs Python (sigma-c-framework) in
        the browser using Pyodide.

        Returns:
            Complete HTML string.
        """
        return """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sigma-C Pyodide Demo</title>
    <script src="https://cdn.jsdelivr.net/pyodide/v0.25.1/full/pyodide.js"></script>
    <style>
        body { font-family: monospace; max-width: 700px; margin: 40px auto; }
        pre { background: #f4f4f4; padding: 16px; overflow-x: auto; }
        button { padding: 8px 20px; cursor: pointer; }
        #output { white-space: pre-wrap; }
    </style>
</head>
<body>
    <h1>Sigma-C in the Browser (Pyodide)</h1>
    <p>Running sigma-c-framework via Python-in-WebAssembly.</p>
    <button id="run" disabled>Loading Pyodide...</button>
    <pre id="output"></pre>

    <script>
    async function main() {
        const output = document.getElementById('output');
        const btn = document.getElementById('run');

        output.textContent = 'Loading Pyodide...\\n';
        let pyodide = await loadPyodide();
        output.textContent += 'Installing sigma-c-framework...\\n';
        await pyodide.loadPackage('micropip');
        await pyodide.runPythonAsync(`
import micropip
await micropip.install(['numpy', 'scipy', 'sigma-c-framework'])
        `);
        output.textContent += 'Ready!\\n\\n';
        btn.textContent = 'Run Analysis';
        btn.disabled = false;

        btn.onclick = async () => {
            output.textContent = '';
            await pyodide.runPythonAsync(`
import numpy as np
from sigma_c import Universe

mag = Universe.magnetic()
temps = np.linspace(1.0, 3.5, 60)
Tc = 2.0 / np.log(1 + np.sqrt(2))
M = np.array([(max(0, (Tc - T)**0.125) if T < Tc else 0.0) for T in temps])
M += np.random.normal(0, 0.02, len(M))
M = np.clip(M, 0, None)

result = mag.compute_susceptibility(temps, M)
print(f"Exact Tc:    {Tc:.5f}")
print(f"Detected Tc: {result['sigma_c']:.5f}")
print(f"Error:       {abs(result['sigma_c'] - Tc):.5f}")
print(f"Kappa:       {result['kappa']:.1f}")
            `);
            output.textContent = pyodide.runPython('import sys; sys.stdout.getvalue()') || output.textContent;
        };
    }
    main();
    </script>
</body>
</html>
"""

    def build(self, output_dir: Optional[str] = None):
        """
        Write all generated artifacts to disk.

        Args:
            output_dir: Target directory (default: self.output_dir).
        """
        out = output_dir or self.output_dir
        os.makedirs(out, exist_ok=True)

        js_path = os.path.join(out, 'sigma_c.js')
        with open(js_path, 'w', encoding='utf-8') as f:
            f.write(self.generate_js_module())

        html_path = os.path.join(out, 'demo.html')
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(self.generate_html_demo())

        pyodide_path = os.path.join(out, 'demo_pyodide.html')
        with open(pyodide_path, 'w', encoding='utf-8') as f:
            f.write(self.generate_pyodide_demo())

        return {
            'js_module': js_path,
            'html_demo': html_path,
            'pyodide_demo': pyodide_path,
        }

    def serve(self, port: int = 8080, directory: Optional[str] = None):
        """
        Start a local HTTP server to preview the browser demo.

        Args:
            port: Port number.
            directory: Directory to serve (default: output_dir).
        """
        import http.server
        import functools

        serve_dir = directory or self.output_dir
        handler = functools.partial(
            http.server.SimpleHTTPRequestHandler,
            directory=serve_dir,
        )
        server = http.server.HTTPServer(('', port), handler)
        print(f"Serving Sigma-C demo at http://localhost:{port}/")
        print("Press Ctrl+C to stop.")
        server.serve_forever()


class PyodideBridge:
    """
    Interface for running Sigma-C inside Pyodide (Python-in-browser).

    When sigma-c-framework is installed in Pyodide via micropip,
    this class provides a simplified API for browser-based analysis.

    Usage (in Pyodide):
        from sigma_c.api.wasm import PyodideBridge

        bridge = PyodideBridge()
        result = bridge.analyze([0, 0.1, 0.2, 0.3, 0.4], [1, 0.9, 0.5, 0.2, 0.1])
        print(result)  # JSON string for JavaScript consumption
    """

    def __init__(self):
        self._engine = Engine()

    def analyze(self, epsilon: list, observable: list) -> str:
        """
        Run analysis and return JSON (convenient for JS interop).

        Args:
            epsilon: Control parameter values.
            observable: Observable values.

        Returns:
            JSON string with results.
        """
        eps = np.array(epsilon, dtype=np.float64)
        obs = np.array(observable, dtype=np.float64)
        result = self._engine.compute_susceptibility(eps, obs)

        return json.dumps({
            'sigma_c': float(result['sigma_c']),
            'kappa': float(result['kappa']),
            'chi_max': float(result['chi_max']),
        })

    def analyze_dict(self, epsilon: list, observable: list) -> Dict[str, float]:
        """
        Run analysis and return a Python dict.

        Args:
            epsilon: Control parameter values.
            observable: Observable values.

        Returns:
            Dictionary with sigma_c, kappa, chi_max.
        """
        eps = np.array(epsilon, dtype=np.float64)
        obs = np.array(observable, dtype=np.float64)
        result = self._engine.compute_susceptibility(eps, obs)

        return {
            'sigma_c': float(result['sigma_c']),
            'kappa': float(result['kappa']),
            'chi_max': float(result['chi_max']),
        }
